function ticketsCall() {
  const tickets = [
    {
      id: 37904,
      ticketOwner: 'Willow Pagac' ,
      company: 'engage revolutionary web services',
      title: 'mollitia voluptas minima',
      priority: 'Urgent',
      details: {
        userTitleInitial: 'Customer',
        userInitial: 'Terrance',
        userIdInitial: 39112,
        contentInitial: 'Qui minus necessitatibus debitis eos aliquam. Corporis aliquam eum pariatur veniam et porro ullam. Voluptatem et totam inventore vitae consequatur.',
      },
    },
    {
      id: 18883,
      ticketOwner: 'Sheila Conn' ,
      company: 'syndicate B2B interfaces',
      title: 'vero voluptates recusandae',
      priority: 'Urgent',
      details: {
        userTitleInitial: 'Admin',
        userInitial: 'Taylor',
        userIdInitial: 41133,
        contentInitial: 'Nihil nisi quos corrupti tempora sed architecto impedit nihil sunt. Doloribus consequatur nisi et nostrum incidunt harum maxime id. Autem fugit aut nihil. Ut rerum sed qui.',
      },
    },
    {
      id: 64501,
      ticketOwner: 'Lilian Greenfelder' ,
      company: 'engineer granular metrics',
      title: 'dolor quis quae',
      priority: 'Urgent',
      details: {
        userTitleInitial: 'Customer',
        userInitial: 'Lesly',
        userIdInitial: 18947,
        contentInitial: 'Consectetur dolores et et officia rerum hic. Rem inventore atque. Ab ea ratione iure quidem est. Delectus nihil enim consectetur autem voluptas quae est ut possimus.',
      },
    },
    {
      id: 13036,
      ticketOwner: 'Ted Harris' ,
      company: 'optimize transparent ROI',
      title: 'cumque molestiae modi',
      priority: 'High',
      details: {
        userTitleInitial: 'Tech',
        userInitial: 'Dexter',
        userIdInitial: 57383,
        contentInitial: 'Debitis quo beatae ut cumque. Est facere provident quidem facere. A et voluptates itaque. Necessitatibus et at quae atque quia similique aperiam eos.',
      },
    },
    {
      id: 17241,
      ticketOwner: 'Danny Gutmann' ,
      company: 'transition killer communities',
      title: 'quo repellendus iure',
      priority: 'Urgent',
      details: {
        userTitleInitial: 'Tech',
        userInitial: 'Baylee',
        userIdInitial: 65941,
        contentInitial: 'Ab ut molestias iusto qui quia. Quis est deleniti sed sed optio doloribus. Ea consequuntur voluptatem voluptates tempora eos laudantium.',
      },
    },
    {
      id: 93691,
      ticketOwner: 'Anahi McCullough' ,
      company: 'facilitate value-added e-commerce',
      title: 'est est et',
      priority: 'High',
      details: {
        userTitleInitial: 'Tech',
        userInitial: 'Kiera',
        userIdInitial: 86665,
        contentInitial: 'Tenetur dolores et esse sit et. Optio ipsam ad. Quasi quo quia enim voluptatum hic rem quaerat. Cumque consequuntur placeat. Sint omnis doloribus ea nesciunt ut est. Doloribus illo aut vitae.',
      },
    },
    {
      id: 63674,
      ticketOwner: 'Jane Stehr' ,
      company: 'innovate bricks-and-clicks solutions',
      title: 'dolorum aut beatae',
      priority: 'Low',
      details: {
        userTitleInitial: 'Admin',
        userInitial: 'Rita',
        userIdInitial: 99293,
        contentInitial: 'Id minus rerum consectetur quaerat ad. Nisi et neque. Eum et aliquam a dolorem. Repellat velit et maiores. Sit rerum earum.',
      },
    },
    {
      id: 22243,
      ticketOwner: 'Florence Graham' ,
      company: 'streamline efficient blockchains',
      title: 'adipisci deleniti perferendis',
      priority: 'Low',
      details: {
        userTitleInitial: 'Customer',
        userInitial: 'Dax',
        userIdInitial: 84326,
        contentInitial: 'Repudiandae nobis optio omnis ipsum voluptatem ea quas laboriosam quos. Consequatur amet eum. Doloremque enim consequatur. Repellendus autem incidunt magni ad. Sunt aut possimus ut quia et quisquam.',
      },
    },
    {
      id: 99060,
      ticketOwner: 'Gaylord Muller' ,
      company: 'iterate cross-media content',
      title: 'ut ut esse',
      priority: 'Urgent',
      details: {
        userTitleInitial: 'Admin',
        userInitial: 'Wilburn',
        userIdInitial: 74932,
        contentInitial: 'Reiciendis consequatur modi nesciunt autem veritatis officia sit. Architecto laudantium itaque nisi placeat dolores molestiae accusantium sit molestiae. Aut doloribus magnam adipisci enim doloribus consequatur cum neque amet. Voluptatem cupiditate commodi saepe voluptate corporis.',
      },
    },
    {
      id: 35336,
      ticketOwner: 'Loma Dare' ,
      company: 'aggregate global users',
      title: 'necessitatibus rerum minus',
      priority: 'Urgent',
      details: {
        userTitleInitial: 'Tech',
        userInitial: 'Ansel',
        userIdInitial: 65565,
        contentInitial: 'Exercitationem sunt officia vitae sed nihil facere labore. Vel quod reiciendis fugit nihil molestiae quod eum neque. Maiores consequatur praesentium nostrum modi iure incidunt et repellat. Quidem ab rerum sunt. Nam qui placeat totam aut aliquid eum cumque.',
      },
    },
    {
      id: 38944,
      ticketOwner: 'Sebastian Olson' ,
      company: 'unleash back-end e-business',
      title: 'error minima molestiae',
      priority: 'Urgent',
      details: {
        userTitleInitial: 'Admin',
        userInitial: 'Mikel',
        userIdInitial: 23674,
        contentInitial: 'Harum facilis est consequuntur in. Qui in eaque rerum ex enim. Quae reprehenderit architecto natus cumque temporibus unde eaque eius error.',
      },
    },
    {
      id: 94071,
      ticketOwner: 'Torrey Heidenreich' ,
      company: 'revolutionize world-class blockchains',
      title: 'quisquam vel minima',
      priority: 'Urgent',
      details: {
        userTitleInitial: 'Admin',
        userInitial: 'Lolita',
        userIdInitial: 81884,
        contentInitial: 'Sapiente quaerat vero necessitatibus deserunt corporis deleniti fuga atque impedit. Est atque tempora quidem ullam et dolor vel. Facere sed aut fugiat aut non maiores.',
      },
    },
    {
      id: 68549,
      ticketOwner: 'Timothy Wolff' ,
      company: 'harness cross-platform e-business',
      title: 'pariatur praesentium necessitatibus',
      priority: 'Urgent',
      details: {
        userTitleInitial: 'Tech',
        userInitial: 'Delphia',
        userIdInitial: 46736,
        contentInitial: 'Tempora hic commodi minus ut. Facilis et qui ut architecto corporis. Pariatur esse occaecati tempora ducimus.',
      },
    },
    {
      id: 80555,
      ticketOwner: 'Jordon Kunze' ,
      company: 'embrace open-source networks',
      title: 'possimus et ut',
      priority: 'High',
      details: {
        userTitleInitial: 'Admin',
        userInitial: 'Casimer',
        userIdInitial: 66998,
        contentInitial: 'Soluta amet pariatur. Sed vitae aperiam aliquam cupiditate vitae ipsum officia dolorum eos. Vitae voluptatum ut quam quod qui dicta quisquam libero quis. Ipsam rerum voluptatem nihil nemo ut. Nisi deserunt architecto est ex consequatur. Voluptate tempore vitae.',
      },
    },
    {
      id: 51971,
      ticketOwner: 'Henri Schneider' ,
      company: 'repurpose granular communities',
      title: 'est expedita accusamus',
      priority: 'Low',
      details: {
        userTitleInitial: 'Tech',
        userInitial: 'Richie',
        userIdInitial: 35049,
        contentInitial: 'Qui perspiciatis sed. Dolores dolores vitae incidunt ut. Voluptatem praesentium suscipit eligendi repellendus. Omnis quia alias fugiat aut quisquam ab error exercitationem. Sapiente incidunt qui nihil. Aut dignissimos veniam sint expedita.',
      },
    },
    {
      id: 83140,
      ticketOwner: 'Curt Hahn' ,
      company: 'scale sticky schemas',
      title: 'vel nihil suscipit',
      priority: 'Mid',
      details: {
        userTitleInitial: 'Customer',
        userInitial: 'Darrin',
        userIdInitial: 46107,
        contentInitial: 'Consequatur non occaecati porro necessitatibus ut maxime. Itaque et omnis optio qui id sunt exercitationem. Aperiam et et.',
      },
    },
    {
      id: 27327,
      ticketOwner: 'Ahmed Reichert' ,
      company: 'streamline enterprise networks',
      title: 'magni voluptas odit',
      priority: 'High',
      details: {
        userTitleInitial: 'Admin',
        userInitial: 'Theo',
        userIdInitial: 53377,
        contentInitial: 'Commodi excepturi earum recusandae repellat enim dolore maxime. Velit ipsum reprehenderit odio. Corrupti vel eum voluptas voluptatum eos ut. Quibusdam debitis consequatur neque harum et odit. Alias est sint ipsam repudiandae porro illo cupiditate. Architecto quibusdam doloremque molestiae necessitatibus quia illum ea.',
      },
    },
    {
      id: 36641,
      ticketOwner: 'Karson Mitchell' ,
      company: 'transition distributed blockchains',
      title: 'sunt itaque dignissimos',
      priority: 'Urgent',
      details: {
        userTitleInitial: 'Admin',
        userInitial: 'Dan',
        userIdInitial: 20231,
        contentInitial: 'Sit necessitatibus ut ullam sit est velit. Qui ab illo eveniet et voluptates cupiditate expedita id sed. Explicabo quod laboriosam aliquam id molestiae ut et ipsum. Occaecati quis consectetur animi sint quam reprehenderit ad corrupti ea.',
      },
    },
    {
      id: 90842,
      ticketOwner: 'Giles Koelpin' ,
      company: 'target bleeding-edge eyeballs',
      title: 'suscipit quidem id',
      priority: 'Low',
      details: {
        userTitleInitial: 'Customer',
        userInitial: 'Earl',
        userIdInitial: 29981,
        contentInitial: 'Eos veritatis corporis quo iure sapiente deleniti voluptate qui. Quae qui eum optio et est laborum. Deserunt laborum odit et soluta qui expedita.',
      },
    },
    {
      id: 90791,
      ticketOwner: 'Malcolm Beer' ,
      company: 'reintermediate dot-com niches',
      title: 'aliquid quas nihil',
      priority: 'Low',
      details: {
        userTitleInitial: 'Tech',
        userInitial: 'Micaela',
        userIdInitial: 77993,
        contentInitial: 'Non qui voluptatem amet asperiores. Perferendis omnis vero omnis velit eius sit aut molestiae quidem. Rem impedit officiis rerum labore totam quis consectetur et. Ea sit nobis ducimus reiciendis ipsam quis laboriosam minus quia. Sapiente dolor deleniti magni occaecati ut.',
      },
    },
    {
      id: 51500,
      ticketOwner: 'Chloe Schiller' ,
      company: 'incubate killer networks',
      title: 'qui eum eius',
      priority: 'Mid',
      details: {
        userTitleInitial: 'Admin',
        userInitial: 'Meaghan',
        userIdInitial: 64743,
        contentInitial: 'Pariatur sunt aut porro explicabo quam saepe. Amet et iste sunt unde. Sapiente iure consequatur aut voluptas ipsam aut et. Tempora odit facere blanditiis expedita. Mollitia excepturi illum est animi dolor quae quaerat voluptatem vel. Et aut est consectetur tempore id odio officiis similique minus.',
      },
    },
    {
      id: 35086,
      ticketOwner: 'Arianna Herzog' ,
      company: 'transition robust users',
      title: 'consequatur nulla id',
      priority: 'High',
      details: {
        userTitleInitial: 'Admin',
        userInitial: 'Jaquan',
        userIdInitial: 33577,
        contentInitial: 'Quo vitae cumque omnis quia sit qui enim. Vitae est quia quas possimus fuga non et quis consequatur. Accusamus voluptatem dolores reprehenderit quae odio excepturi id. Quis commodi ipsam non. Ipsa aliquid et reiciendis ut architecto sunt.',
      },
    },
    {
      id: 78202,
      ticketOwner: 'Nikolas Schowalter' ,
      company: 'orchestrate next-generation infrastructures',
      title: 'voluptatem ab autem',
      priority: 'High',
      details: {
        userTitleInitial: 'Admin',
        userInitial: 'Jairo',
        userIdInitial: 38423,
        contentInitial: 'Iure nisi et ipsam et placeat culpa voluptatem qui maiores. Officia et eum molestiae. Non nostrum aut quia et labore qui. Ut corporis perferendis ut.',
      },
    },
    {
      id: 14940,
      ticketOwner: 'Antonietta Breitenberg' ,
      company: 'incentivize B2B partnerships',
      title: 'rerum est quod',
      priority: 'Low',
      details: {
        userTitleInitial: 'Tech',
        userInitial: 'Haley',
        userIdInitial: 97606,
        contentInitial: 'Esse laudantium at. Delectus fugiat ut necessitatibus consequuntur. Porro fugit nostrum enim aperiam sint consequatur. Fuga aut non dignissimos.',
      },
    },
    {
      id: 42150,
      ticketOwner: 'Shayna Wilkinson' ,
      company: 'scale wireless interfaces',
      title: 'aperiam esse ullam',
      priority: 'Urgent',
      details: {
        userTitleInitial: 'Tech',
        userInitial: 'Nella',
        userIdInitial: 37070,
        contentInitial: 'Illum ut harum eligendi. Qui magnam deleniti perferendis. Accusamus ratione dicta rerum voluptatem cumque nulla nisi. Ut ipsum culpa maxime ipsam autem odit odio perspiciatis illum.',
      },
    },
    {
      id: 41935,
      ticketOwner: 'Laurie White' ,
      company: 'aggregate cutting-edge architectures',
      title: 'ut laboriosam est',
      priority: 'High',
      details: {
        userTitleInitial: 'Tech',
        userInitial: 'Theo',
        userIdInitial: 47180,
        contentInitial: 'Fuga rerum voluptatibus. Laborum sit quia omnis nobis voluptas sapiente. Qui quia et debitis quas. Sed cumque illum nulla molestias sit rerum et quasi sed.',
      },
    },
    {
      id: 77675,
      ticketOwner: 'Carolina Windler' ,
      company: 'reinvent real-time convergence',
      title: 'reprehenderit voluptate tenetur',
      priority: 'Low',
      details: {
        userTitleInitial: 'Admin',
        userInitial: 'Maya',
        userIdInitial: 55215,
        contentInitial: 'Suscipit repudiandae aut qui odit. Eum illo eius blanditiis sint aut impedit voluptatem. Dolore recusandae et sunt.',
      },
    },
    {
      id: 47900,
      ticketOwner: 'Reuben Sporer' ,
      company: 'synergize plug-and-play e-markets',
      title: 'maiores et dolorum',
      priority: 'Urgent',
      details: {
        userTitleInitial: 'Tech',
        userInitial: 'Sophia',
        userIdInitial: 55732,
        contentInitial: 'Est fuga itaque explicabo ut dolore. Ut sint illum occaecati voluptas veritatis ut autem. In consequatur est eum id et impedit atque. Praesentium sapiente laudantium consequatur esse consequatur nostrum commodi.',
      },
    },
    {
      id: 16616,
      ticketOwner: 'Desmond OHara',
      company: 'cultivate leading-edge platforms',
      title: 'labore nisi officiis',
      priority: 'Mid',
      details: {
        userTitleInitial: 'Tech',
        userInitial: 'Alec',
        userIdInitial: 50774,
        contentInitial: 'Ex id nulla optio id. Molestiae similique corporis expedita. Et quas voluptatibus possimus ut fugit.',
      },
    },
    {
      id: 81946,
      ticketOwner: 'Ivory Marvin' ,
      company: 'productize extensible e-commerce',
      title: 'est dolores qui',
      priority: 'Urgent',
      details: {
        userTitleInitial: 'Customer',
        userInitial: 'Thad',
        userIdInitial: 54899,
        contentInitial: 'Impedit ea nisi quis culpa dolores rerum itaque quibusdam rem. Laudantium dolor est est voluptatibus sapiente qui dolor beatae. Maiores aspernatur ut.',
      },
    },
    {
      id: 39608,
      ticketOwner: 'Gianni Adams' ,
      company: 'grow innovative initiatives',
      title: 'consequatur aspernatur reprehenderit',
      priority: 'High',
      details: {
        userTitleInitial: 'Admin',
        userInitial: 'Willow',
        userIdInitial: 14656,
        contentInitial: 'Tempora dolorem cumque consequuntur omnis vero. Consequuntur animi aut et eos omnis est ut aut soluta. Aut eum iure esse ea quia. Molestiae consequuntur molestiae laborum et et cupiditate autem repellendus.',
      },
    },
    {
      id: 56622,
      ticketOwner: 'Stefan Jakubowski' ,
      company: 'visualize intuitive partnerships',
      title: 'pariatur sed corrupti',
      priority: 'Low',
      details: {
        userTitleInitial: 'Admin',
        userInitial: 'Pink',
        userIdInitial: 76557,
        contentInitial: 'Qui sunt placeat ipsa. Saepe delectus sint quia et architecto nulla harum quis. Molestiae a beatae quasi deleniti quo debitis et eum rerum.',
      },
    },
    {
      id: 88972,
      ticketOwner: 'Justina Borer' ,
      company: 'brand B2B vortals',
      title: 'a possimus voluptate',
      priority: 'Mid',
      details: {
        userTitleInitial: 'Tech',
        userInitial: 'Willow',
        userIdInitial: 57350,
        contentInitial: 'Dignissimos facilis vero laudantium ipsa eius aut. Dolores expedita possimus. Quaerat enim sapiente sunt et illum cum totam ut. Non qui ullam eum sed et. Voluptatem dolorum temporibus cum facilis tempore.',
      },
    },
    {
      id: 79028,
      ticketOwner: 'Destiny Wilderman' ,
      company: 'streamline back-end e-services',
      title: 'eligendi nisi maiores',
      priority: 'High',
      details: {
        userTitleInitial: 'Customer',
        userInitial: 'Bertrand',
        userIdInitial: 73798,
        contentInitial: 'Facilis aut repellendus. Libero ab modi commodi ad velit voluptas. Quis ut temporibus corrupti. Eos impedit architecto officiis tempora neque magnam debitis atque dolorem.',
      },
    },
    {
      id: 71171,
      ticketOwner: 'Jazlyn Ritchie' ,
      company: 'architect dot-com bandwidth',
      title: 'corporis error odit',
      priority: 'High',
      details: {
        userTitleInitial: 'Admin',
        userInitial: 'Shane',
        userIdInitial: 77051,
        contentInitial: 'In aspernatur totam iure nemo veritatis. Eos quas nemo eius. Est inventore voluptas nihil. Dolor expedita veritatis. Non quasi voluptas blanditiis quisquam vero fugit.',
      },
    },
    {
      id: 42222,
      ticketOwner: 'Aylin Grant' ,
      company: 'synthesize strategic solutions',
      title: 'eaque ad et',
      priority: 'Mid',
      details: {
        userTitleInitial: 'Admin',
        userInitial: 'Ford',
        userIdInitial: 22482,
        contentInitial: 'Necessitatibus saepe illo veniam. Porro ut libero iste consequatur rerum sint. Illum hic illo voluptatem doloremque impedit nostrum expedita. Autem earum quia cumque eum dolore assumenda iste praesentium. Quam quasi velit. Consequatur omnis necessitatibus eaque id.',
      },
    },
    {
      id: 20001,
      ticketOwner: 'Gwen Feeney' ,
      company: 'transform vertical convergence',
      title: 'deserunt vitae illum',
      priority: 'Urgent',
      details: {
        userTitleInitial: 'Tech',
        userInitial: 'Lexie',
        userIdInitial: 39469,
        contentInitial: 'Neque libero natus quidem dolorem quas dolorem amet qui voluptatem. Illum delectus perspiciatis possimus. Et quia quis saepe rerum quam. Dicta officiis delectus asperiores sint.',
      },
    },
    {
      id: 17971,
      ticketOwner: 'Edgar Tremblay' ,
      company: 'leverage viral systems',
      title: 'doloremque facere molestias',
      priority: 'High',
      details: {
        userTitleInitial: 'Admin',
        userInitial: 'Deontae',
        userIdInitial: 53047,
        contentInitial: 'Ea quibusdam id blanditiis omnis quae ea esse soluta. Pariatur omnis dignissimos optio dolores vero voluptatem et maiores velit. Consectetur omnis cum dolore mollitia iusto repellendus quasi porro.',
      },
    },
    {
      id: 47376,
      ticketOwner: 'Jazmin Streich' ,
      company: 'enhance holistic interfaces',
      title: 'repudiandae eius sit',
      priority: 'Low',
      details: {
        userTitleInitial: 'Admin',
        userInitial: 'Caden',
        userIdInitial: 37137,
        contentInitial: 'Debitis deleniti veritatis suscipit asperiores ea consectetur unde nisi. Pariatur dolorem sunt adipisci occaecati omnis nesciunt rem optio. Omnis nihil molestiae. At non aut sit iusto sequi dolorem porro. At saepe amet asperiores similique dolor temporibus mollitia. Recusandae excepturi beatae temporibus.',
      },
    },
    {
      id: 96811,
      ticketOwner: 'Leda Huel' ,
      company: 'iterate rich action-items',
      title: 'eos dolorem et',
      priority: 'Low',
      details: {
        userTitleInitial: 'Admin',
        userInitial: 'Leila',
        userIdInitial: 50281,
        contentInitial: 'Enim sapiente qui eveniet illum nihil amet. Blanditiis inventore et qui quis quisquam et exercitationem maxime aut. Qui nostrum iure ab numquam et quasi harum nihil. Provident nulla earum vel velit pariatur veritatis consequuntur ratione eos. Consequatur nostrum est rerum qui et. Magni id odit est dignissimos.',
      },
    },
    {
      id: 90009,
      ticketOwner: 'Jeffery Franecki' ,
      company: 'synergize intuitive systems',
      title: 'distinctio alias quia',
      priority: 'High',
      details: {
        userTitleInitial: 'Admin',
        userInitial: 'Hailee',
        userIdInitial: 13791,
        contentInitial: 'Vero dolorem eius voluptate. Qui neque inventore voluptas qui. Temporibus quia recusandae consequatur sit magni perferendis ut ipsam.',
      },
    },
    {
      id: 21196,
      ticketOwner: 'Tevin Zemlak' ,
      company: 'seize front-end interfaces',
      title: 'ex assumenda sequi',
      priority: 'Urgent',
      details: {
        userTitleInitial: 'Tech',
        userInitial: 'Walker',
        userIdInitial: 33664,
        contentInitial: 'Et vero officia maiores aut. Laboriosam ipsam eligendi dicta necessitatibus necessitatibus rerum quis minus nulla. Sit ut cum tempora tenetur est molestiae nam.',
      },
    },
    {
      id: 80884,
      ticketOwner: 'Jaunita Feest' ,
      company: 'integrate plug-and-play vortals',
      title: 'quae id aut',
      priority: 'High',
      details: {
        userTitleInitial: 'Tech',
        userInitial: 'Isaiah',
        userIdInitial: 49431,
        contentInitial: 'Tenetur explicabo et. Sit consequatur in error atque blanditiis autem est labore aut. Repellat atque ut quis. Omnis rem in omnis aspernatur id voluptas qui.',
      },
    },
    {
      id: 14102,
      ticketOwner: 'Jerod Friesen' ,
      company: 'exploit user-centric web services',
      title: 'fuga id eligendi',
      priority: 'Mid',
      details: {
        userTitleInitial: 'Customer',
        userInitial: 'Delores',
        userIdInitial: 51558,
        contentInitial: 'Delectus tempora enim quae sit sed. Harum perferendis delectus hic non ut rerum quas et rerum. Sit porro nobis nulla est maiores molestiae ut. Sit quo accusamus est repellendus dolores aut. Libero eius eos.',
      },
    },
    {
      id: 46471,
      ticketOwner: 'Tillman Blick' ,
      company: 'morph impactful schemas',
      title: 'in et a',
      priority: 'Urgent',
      details: {
        userTitleInitial: 'Admin',
        userInitial: 'Carley',
        userIdInitial: 10513,
        contentInitial: 'Et blanditiis quos ex nihil amet. Voluptate eveniet est hic voluptatem voluptatem id. Neque ea ut. Dolore fuga totam voluptatem.',
      },
    },
    {
      id: 95962,
      ticketOwner: 'Grady Botsford' ,
      company: 'engage innovative blockchains',
      title: 'earum et et',
      priority: 'Low',
      details: {
        userTitleInitial: 'Admin',
        userInitial: 'Myrna',
        userIdInitial: 90076,
        contentInitial: 'Esse harum fugit. Voluptate aut aut harum ut facilis consectetur et et. Exercitationem voluptatum veniam dolorum tempora et non quas sunt. Placeat et quia est accusantium omnis deserunt at. Et veniam dolor.',
      },
    },
    {
      id: 39736,
      ticketOwner: 'Fatima Herman' ,
      company: 'deploy intuitive interfaces',
      title: 'quis eaque voluptatem',
      priority: 'Urgent',
      details: {
        userTitleInitial: 'Tech',
        userInitial: 'Aracely',
        userIdInitial: 30722,
        contentInitial: 'Nihil aut perspiciatis. Officia quasi qui in ullam excepturi inventore rerum. Dignissimos voluptatem voluptatem debitis voluptate qui et ut. Impedit quo maxime possimus tempore. Neque molestiae molestiae sed repellat sunt unde ea. Qui praesentium asperiores voluptas soluta facilis.',
      },
    },
    {
      id: 33809,
      ticketOwner: 'Johnpaul Huels' ,
      company: 'empower sexy infomediaries',
      title: 'nesciunt qui a',
      priority: 'Low',
      details: {
        userTitleInitial: 'Tech',
        userInitial: 'General',
        userIdInitial: 75082,
        contentInitial: 'Expedita cumque quisquam eum et officiis quae dignissimos alias saepe. Dolorem sed blanditiis quis tempore aut in ut sed. Consequatur facere aut ducimus ut minima sunt nostrum.',
      },
    },
    {
      id: 22594,
      ticketOwner: 'Noelia Gottlieb' ,
      company: 'incubate revolutionary vortals',
      title: 'nesciunt corrupti aut',
      priority: 'High',
      details: {
        userTitleInitial: 'Admin',
        userInitial: 'Layne',
        userIdInitial: 67398,
        contentInitial: 'Modi aut dolores accusantium dignissimos. Eaque sunt enim velit. Excepturi nulla in voluptatum harum soluta. Ut quam aut distinctio odio explicabo ipsum iste. Praesentium dolorem fugit ut. Voluptate ab iure eos in voluptas id exercitationem.',
      },
    },
    {
      id: 65161,
      ticketOwner: 'Noelia McDermott' ,
      company: 'deploy plug-and-play partnerships',
      title: 'rerum occaecati alias',
      priority: 'Urgent',
      details: {
        userTitleInitial: 'Tech',
        userInitial: 'Lilla',
        userIdInitial: 99854,
        contentInitial: 'Quisquam et sit. Fugiat ea error voluptatibus suscipit blanditiis. Occaecati cumque fugit eos. Cumque sit amet libero est ipsam delectus consequatur officia.',
      },
    },
  ];
  
  return tickets;
}

function ticketDetails(id) {
  //console.log('pulling details from the server with id ' + id);
  const details = [
    {
      userTitle: 'Customer',
      user: 'Bonnie',
      userID: 95194,
      content: 'Est aut voluptates nisi. Earum iusto possimus ea est qui quis perferendis tempore. Veritatis itaque aut debitis soluta deleniti cupiditate. Sint quia molestias rerum reiciendis magni. Dignissimos temporibus dicta consequuntur. Est vel reprehenderit omnis voluptas qui rerum.',
    },
    {
      userTitle: 'Customer',
      user: 'Julius',
      userID: 82464,
      content: 'Et optio accusamus at. Voluptatum nihil ex corporis reprehenderit animi sed voluptatem. Placeat expedita nostrum dolor provident numquam quae accusamus voluptatibus. Quia dolores consectetur repudiandae molestias et repudiandae pariatur.',
    },
    {
      userTitle: 'Admin',
      user: 'Kody',
      userID: 53218,
      content: 'Ad sit rerum. Sit perspiciatis esse et minima quae quas quisquam iusto. Soluta quaerat modi.',
    },
    {
      userTitle: 'Customer',
      user: 'Sasha',
      userID: 48050,
      content: 'Hic itaque accusantium sequi pariatur. Dolorem ut in tempore officia est incidunt aliquid aspernatur. Dolores rem repellat id aliquam consequuntur quo sapiente culpa.',
    },
    {
      userTitle: 'Customer',
      user: 'Jaylen',
      userID: 65134,
      content: 'Nobis laborum magni aut voluptas id explicabo occaecati consequuntur qui. Cumque voluptatem explicabo quibusdam unde ut vitae blanditiis aliquid laborum. Cum molestiae consequuntur voluptatem nulla numquam dolorum nesciunt. Repellat nihil autem tempora. Architecto voluptatum eligendi.',
    },
  ];

  return details;
}

export {
  ticketsCall,
  ticketDetails,
};